### ISSUE TITLE
Typogrify makes required changes in endnotes and one story

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/edgar-allan-poe_short-fiction#5]
Your production notes say not to run typogrify on the whole production, but it does make a couple of changes in endnotes and in x-ing-a-paragrab which should be accepted. Also, shouldn't the dash within "damn", line 39 of the latter story, be a two-em dash, not a single-em dash?

**Comment by robinwhittleton** [comment]
Fixed in https://github.com/robinwhittleton/edgar-allan-poe_short-fiction/commit/0fafd166214461f59e27bf6e3de22e2409961f45. Some slightly weird ones there, I think typogrify isn’t necessarily doing the correct thing, but 🤷‍♂️ I also found an issue at the end of ”The Man Who was Used Up” that wasn’t part of the broken other changes; fixed in the same commit.
